STATIC:
  ITERATIONS: 30000
  TEST_ITERATIONS: [7000, 30000]
  SAVE_ITERATIONS: [7000, 30000]
  VIZ_INTERVAL: 10000
  CHECKPOINT_ITERATIONS: [30000]
  POSITION_LR_INIT: 0.00016
  POSITION_LR_FINAL: 0.0000016
  POSITION_LR_DELAT_MULT: 0.01
  POSITION_LR_MAX_STEPS: 30000
  COLOR_LR_INIT: 0.0025
  FEATURE_LR: 0.0025
  OPACITY_LR: 0.05
  SCALING_LR: 0.005
  ROTATION_LR: 0.001
  PERCENT_DENSE: 0.01
  LAMBDA_DSSIM: 0.2
  DENSIFICATION_INTERVAL: 100
  OPACITY_RESET_INTERVAL: 3000
  DENSIFY_FROM_ITER: 500
  DENSIFY_UNTIL_ITER: 15000
  DENSIFY_GRAD_THRESHOLD: 0.0002
  SH_DEGREE: 3
  GRAD_SHRESHOLD: 0.005
  CONST_SCALE: 0.003

SEED: 123
REAL: False

VELOCITY:
  TYPE: Spring_Mass
  PRETRAINED: null
  ITERATIONS: 100
  ITER_REFINE: 3000
  REFINE_VIZ_INTERVAL: 1000
  SAVE_INTERVAL: 100
  VIZ_INTERVAL: 100
  INIT_VELOCITY: [0, 0, 0]
  G: [0, -9.8, 0]

  K_NEIGHBORS: 256
  K_BINDING: 16
  N_SAMPLE: 2048
  N_STEP: 100
  STEP_ADD: 100
  MAX_N_STEP: 500
  N_STEP_ITER: [200, ]

  LAMBDA_DSSIM: 0.2
  LAMBDA_SMOOTH: 0.0
  LAMBDA_CENTER: 0.0
  LAMBDA_PERCEP: 0.0
  OPTIMIZE:
    INIT_VELOCITY_LR: 0.001
    LR_DECAY_STEP: 100
    LR_DECAY_RATE: 0.5
    G_LR: 0.001

  GAUS_CFG:
    OPTIM_GAUS: False

  GAUS_REFINE:
    OPTIM_GAUS: True
    POSITION_LR_FINAL: 0.0000016
    COLOR_LR_INIT: 0.0025
    OPACITY_LR: 0.05
    SCALING_LR: 0.005

  FITTING: True
  FIX_MASS: True
  FIX_K: True
  DAMPING: False
  UNLINEAR_FORCE: True
  OPTIM_G: False
  SOFT_K: False


DYNAMIC:
  TYPE: Spring_Mass
  PRETRAINED: null
  ITERATIONS: 300
  ITER_REFINE: 3000
  REFINE_VIZ_INTERVAL: 1000
  SAVE_INTERVAL: 100
  VIZ_INTERVAL: 100

  LAMBDA_DSSIM: 0.05
  LAMBDA_SMOOTH: 0.0
  LAMBDA_CENTER: 0.0
  LAMBDA_PERCEP: 0.0
  OPTIMIZE:
    K_LR: 0.001
    M_LR: 0.001
    FRIC_K_LR: 0.001
    REBOUND_K_LR: 0.001
    DAMPING_LR: 0.0001
    INIT_VELOCITY_LR: 0.00025
    INTERP_LR: 0.001
    G_LR: 0.0001
    SOFT_LR: 0.001
    K_BC_LR: 0.001

  GAUS_CFG:
    OPTIM_GAUS: True
    POSITION_LR_FINAL: 0.0000016
    COLOR_LR_INIT: 0.0025
    OPACITY_LR: 0.05
    SCALING_LR: 0.005

  K_NEIGHBORS: 256
  K_BINDING: 16
  N_SAMPLE: 2048
  N_STEP: 100
  STEP_ADD: 50
  MAX_N_STEP: 500
  N_STEP_ITER: [100, 200]
  G: [0, -9.8, 0]
  STRETCH_RATIOS: 0.05
  RATIO_FACTOR: 1
  POWER: 0.5

  FITTING: True
  DAMPING: True
  FIX_MASS: True
  FIX_DAMP: True
  FIX_K: True
  UNLINEAR_FORCE: True
  OPTIM_G: False
  SOFT_K: True
  SPRING_BC: False
  OPTIM_DY_VELOCITY: False
  OPTIM_FIXED_DAMP: False
  SINGLE_K: False
  N_FIX_SPRING: 16